# Retrieve books from external source
GET http://localhost:5218/api/books/external?query=123&offset=0&limit=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0Iiwicm9sZSI6IkFkbWluIiwibmJmIjowLCJleHAiOjAsImlzcyI6Ikdvb2RSZWFkcyBBUEkiLCJhdWQiOiJhZG1pbjtyZWFkZXIifQ.TvyclM-S6lTYnlv-Amuva8ufr9TCBlKkfXZzHEIsinY
Accept: application/json
